language: c

compiler:
  - gcc

notifications:
  email:
    on_failure: project@pgrouting.org

branches:
  only:
    - develop

services:
  - postgresql

env:
  - POSTGIS_VERSION=1.5
  - POSTGIS_VERSION=2.0

  #matrix:
    #- POSTGRESQL_VERSION=8.4 POSTGIS_VERSION=1.5
    #- POSTGRESQL_VERSION=9.0 POSTGIS_VERSION=1.5
    #- POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=1.5
    #- POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.0
    #- POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.0

    #- POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.1
    #- POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.1
    #- POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.1

install:
  - ./tools/travis/pgrouting_install.sh $POSTGIS_VERSION

before_script:
  #- ./tools/travis/pgrouting_prepare.sh $POSTGIS_VERSION

script: 
  - ./tools/travis/pgrouting_build.sh $POSTGIS_VERSION

after_script: 
  - ./tools/travis/pgrouting_test.sh $POSTGIS_VERSION

after_success:
  #- ./tools/travis/pgrouting_deploy.sh $POSTGIS_VERSION

