# ------------------------------------------------------------------------------
# Travis CI scripts 
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------

language: cpp

sudo: required
dist: trusty

compiler:
  - gcc

notifications:
  email:
    - vicky_vergara@hotmail.com
  on_failure: allways
  on_success: change

branches:
  only:
    - new-travis-dev

addons:
  postgresql: 9.2
#  postgresql: 9.1
  # Dependencies on linux.
  apt:
    sources:
      # For gcc >= 4.8
      - ubuntu-toolchain-r-test
      # For cmake >= 2.8.8 (for CMakePackageConfigHelpers)
      - kubuntu-backports
      - boost-latest
    packages:
      - cmake
      - libboost-thread-dev
      - libboost-graph-dev
      - libcgal-dev
      - postgresql-server-dev-all
      - postgresql-common



env:
  matrix:
    - POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.1
#    - POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.1


before_install:
#  - export PATH=/usr/lib/postgresql/$POSTGRESQL_VERSION/bin:$PATH

#install:

#before_script:

script: 
  - ./tools/travis/pgrouting_build.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

#after_script: 

#after_success:

