# ------------------------------------------------------------------------------
# Travis CI scripts 
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------

language: cpp

sudo: required
dist: trusty

compiler:
  - gcc-4.8

notifications:
  email:
    on_failure: vicky@georepublic.com

branches:
  only:
    - new-travis-dev

addons:
#  postgresql: "9.4"
#  postgresql: "9.3"
#  postgresql: "9.2"
  postgresql: 9.1

  # Dependencies on linux.
  apt:
    sources:
      # For gcc >= 4.8
      - ubuntu-toolchain-r-test
      # For cmake >= 2.8.8 (for CMakePackageConfigHelpers)
      - kubuntu-backports
      - boost-latest
    packages:
      - cmake
#      - gcc-4.8
#      - g++-4.8
#      - libboost-dev
      - libboost-thread-dev
#      - libboost-program-options-dev
#      - libboost1.55-dev
#      - libboost1.55-all-dev
#      - libboost-all-dev
#      - libboost-thread1.55-dev
#      - libboost-program-options1.55-dev
#      - libboost-system-dev
      - libboost-graph-dev
      - libcgal-dev
      - postgresql-server-dev-9.1


#services:
  #- postgresql: 9.1
  #- postgresql: 9.2
  #- postgresql: 9.3

#matrix:
#  env: BUILD_TOOL=cmake
#  include:
#    - os: linux
#      compiler: gcc-4.8


env:
  matrix:
#    - POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.1
#    - POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.1
#    - POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.1
    - POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.1

#    - POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.0
#    - POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.0
#    - POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.0
#    - POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.0

    ## We are NOT supporting these for pgrouting 2.1.0
    #- POSTGRESQL_VERSION=8.4 POSTGIS_VERSION=1.5
    #- POSTGRESQL_VERSION=9.0 POSTGIS_VERSION=1.5
    #- POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=1.5



before_install:
  - cmake --version
  - gcc-4.8 --version

install:
#  - ./tools/travis/pgrouting_install.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

before_script:
#  -

script: 
  - ./tools/travis/pgrouting_build.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

after_script: 
#  - ./tools/travis/pgrouting_prepare.sh $POSTGRESQL_VERSION $POSTGIS_VERSION
#  - ./tools/travis/pgrouting_test.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

after_success:
  #- ./tools/travis/pgrouting_deploy.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

