# ------------------------------------------------------------------------------
# Travis CI scripts 
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------

language: cpp

sudo: required
dist: trusty

compiler:
  - gcc

notifications:
  email:
    - vicky_vergara@hotmail.com
  on_failure: allways
  on_success: change

branches:
  only:
    - new-travis-dev

addons:
  postgresql: 9.2
  postgresql: 9.1
  # Dependencies on linux.
  apt:
    sources:
      # For gcc >= 4.8
      - ubuntu-toolchain-r-test
      # For cmake >= 2.8.8 (for CMakePackageConfigHelpers)
      - kubuntu-backports
      - boost-latest
    packages:
      - cmake
      - libboost-thread-dev
      - libboost-graph-dev
      - libcgal-dev
      - postgresql-server-dev-all



env:
  matrix:
    - POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.1
    - POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.1


before_install:
  - cmake --version
  - gcc-4.8 --version
  - ls /usr/include/postgresql
  - export PATH=/usr/lib/postgresql/$POSTGRESQL_VERSION/bin:$PATH

#install:
#  Installed using apt above

before_script:
#  
  - psql --version
  - psql -U postgres -c "CREATE DATABASE routing;"
  - psql -d routing -U postgres -c "CREATE EXTENSION postgis;"
#  - psql -U postgres -c "SELECT version();"
#  - psql -d routing -U postgres -c "SELECT postgis_full_version();"



script: 
  - ./tools/travis/pgrouting_build.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

after_script: 
  #  - psql --version
  #  - psql -U postgres -c "SELECT version();"
  #  - psql -U postgres -c "CREATE DATABASE routing;"
  #  - psql -d routing -U postgres -c "CREATE EXTENSION postgis;"
  #  - psql -d routing -U postgres -c "SELECT postgis_full_version();"
  #  - psql -d routing -U postgres -c "CREATE EXTENSION pgrouting;"
  #  - psql -d routing -U postgres -c "SELECT * from pgr_version();"
  #  - ./tools/travis/pgrouting_prepare.sh $POSTGRESQL_VERSION $POSTGIS_VERSION
  - ./tools/travis/pgrouting_test.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

#after_success:
  #- ./tools/travis/pgrouting_deploy.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

