language: c

compiler:
  - gcc

notifications:
  email:
    on_failure: project@pgrouting.org

branches:
  only:
    - develop

services:
  - postgresql

env:
  - POSTGIS_VERSION=1.5
  - POSTGIS_VERSION=2.0

  #matrix:
    #- POSTGRESQL_VERSION=8.4 POSTGIS_VERSION=1.5
    #- POSTGRESQL_VERSION=9.0 POSTGIS_VERSION=1.5
    #- POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=1.5
    #- POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.0
    #- POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.0

    #- POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.1
    #- POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.1
    #- POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.1

install:
  # Add PPA for PostGIS 2.x
  - if [[ "$POSTGIS_VERSION" != "1.5" ]]; then sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable; fi

  # Add PPA for pgRouting Travis
  - sudo apt-add-repository -y ppa:georepublic/pgrouting-travis
  - sudo apt-get -q update

  # Install dependecies
  - sudo apt-get install -q cmake libcgal-dev libboost-graph-dev libboost-thread-dev postgresql-server-dev-all

  # Install PostGIS
  - sudo apt-get install -q postgresql-9.1-postgis

before_script:
  #- run/before/build

script: 
  - ./tools/travis/pgrouting_build.sh $POSTGIS_VERSION

after_script: 
  - ./tools/travis/pgrouting_test.sh $POSTGIS_VERSION

after_success:
  # Do this after success

