# ------------------------------------------------------------------------------
# Travis CI scripts 
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------


dist: trusty

sudo: required


notifications:
  email:
    on_failure: vicky_vergara@hotmail.com

branches:
  only:
    - master
    - develop
    - cmake-improve-2.2

addons:
  postgresql: "9.2"
  postgresql: "9.3"
  postgresql: "9.4"

services:
  #- postgresql: 9.1
  #- postgresql: 9.2
  #- postgresql: 9.3

    
language: c

compiler:
  - gcc

env:
  - POSTGRESQL_VERSION=9.1
  - POSTGRESQL_VERSION=9.2
  - POSTGRESQL_VERSION=9.3
  - POSTGRESQL_VERSION=9.4

# excecuted. So things have to be tested oe by one.
addons:
  apt:
    sources:
      # For gcc >= 4.8
      # - ubuntu-toolchain-r-test
      # For cmake >= 2.8.8 (for CMakePackageConfigHelpers)
      #- kubuntu-backports
      - boost-latest
    packages:
      #- cmake
      - libboost-thread-dev
      - libboost-graph-dev
      - libcgal-dev
      - postgresql-server-dev-all


before_script:
  - export PATH=/usr/lib/postgresql/$POSTGRESQL_VERSION/bin:$PATH     # Add our chosen PG version to the path
  - sudo /etc/init.d/postgresql stop                         # Stop whichever version of PG that travis started
  - sudo /etc/init.d/postgresql start $POSTGRESQL_VERSION             # Start the version of PG that we want to test
  #- sudo apt-get install postgresql-server-dev-$POSTGRESQL_VERSION    # Required for PGXS
  - sudo apt-get install postgresql-common                   # Required for extension support files
  #- createdb hll_regress                                     # Create the test database

#env:
  #matrix:
    #- POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.1
    #- POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.1
    #- POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.1
    #- POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.1

    #- POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.0
    #- POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.0
    #- POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.0
    #- POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.0

    ## We are NOT supporting these for pgrouting 2.1.0
    #- POSTGRESQL_VERSION=8.4 POSTGIS_VERSION=1.5
    #- POSTGRESQL_VERSION=9.0 POSTGIS_VERSION=1.5
    #- POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=1.5

install:
  #- ./tools/travis/pgrouting_install.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

before_script:
  #-

script: 
  - ./tools/travis/pgrouting_build.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

after_script: 
  #- ./tools/travis/pgrouting_prepare.sh $POSTGRESQL_VERSION $POSTGIS_VERSION
  - ./tools/travis/pgrouting_test.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

after_success:
  #- ./tools/travis/pgrouting_deploy.sh $POSTGRESQL_VERSION $POSTGIS_VERSION
