# ------------------------------------------------------------------------------
# appVeyor script
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------

version: 2.3.{build}

branches:
  only:
    - test/appveyor
    - master
    - develop
    - appveyor/cache

image: Visual Studio 2013
configuration: Release
platform: x64

clone_depth: 1
clone_folder: c:\build\pgrouting

cache:
  - downloads -> appveyor.yml
  - c:\build\local\msvc120\x68 -> appveyor
  #- C:\local\boost_1_58_0 -> appveyor.yml
  #- c:\local -> appveyor.yml

services:
  - postgresql94

#environment:
#  CONFIGURATION: Release

init:
  - git config --global core.autocrlf false

install:
  - call ci\appveyor\install.bat

  - cd c:\build
  # CGAL 4.8.1
  #- curl -L -O -S -s http://github.com/CGAL/cgal/releases/download/releases/CGAL-4.8.1/CGAL-4.8.1.zip
  #- 7z x CGAL-4.8.1.zip
  - dir
  - mkdir gmp\x64
  - cd gmp\x64
  - curl -L -O -S -s http://cgal.geometryfactory.com/CGAL/precompiled_libs/auxiliary/x64/GMP/5.0.1/gmp-all-CGAL-3.9.zip
  - 7z x gmp-all-CGAL-3.9.zip
  - curl -L -O -S -s http://cgal.geometryfactory.com/CGAL/precompiled_libs/auxiliary/x64/MPFR/3.0.0/mpfr-all-CGAL-3.9.zip
  - 7z x mpfr-all-CGAL-3.9.zip
  - dir

build_script:
  - cd c:\build\pgrouting\tools\windows
  - msbuild_pgrouting.bat 9.4 x64
  - cd c:\build\pgrouting\build\pg94\x64
  - msbuild PGROUTING.sln /target:Build /property:Configuration=%CONFIGURATION%
  - msbuild INSTALL.vcxproj /target:Build /property:Configuration=%CONFIGURATION%
  - copy c:\build\gmp\x64\lib\*.dll C:\Progra~1\PostgreSQL\9.4\bin\

test_script:
  - set PGUSER=postgres
  - set PGPASSWORD=Password12!
  - set PGHOME=C:\Progra~1\PostgreSQL\9.4
  - set PGPORT=5432
  - set PATH=%PATH%;%PGHOME%\bin
  # Execute algorithm test by Cygwin
  - C:\cygwin\bin\bash -lc "cd /cygdrive/c/build/pgrouting && tools/testers/algorithm-tester.pl -psql \"/cygdrive/c/Progra~1/PostgreSQL/9.4/bin/psql\" -ignorenotice"
